In [2]:
import numpy as np
data = np.array([[1], [2], [3]])

In [3]:
data.ndim

2

In [4]:
data

array([[1],
       [2],
       [3]])

In [5]:
a=np.squeeze(data)  #used to reduse dimention, sometime it uses in image proseccing

In [6]:
a

array([1, 2, 3])

In [7]:
a.ndim

1

In [8]:
#repeat
data

array([[1],
       [2],
       [3]])

In [9]:
np.repeat(data, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [10]:
a = np.array([[1, 2], [3, 4]])

In [11]:
a

array([[1, 2],
       [3, 4]])

In [12]:
np.repeat(a, 2) #data repeting 4 time
#use case when image processing sometime we need it.

array([1, 1, 2, 2, 3, 3, 4, 4])

In [13]:
a

array([[1, 2],
       [3, 4]])

In [14]:
np.repeat(a, 2, axis = 1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [15]:
np.repeat(a, 2, axis = 0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [16]:
data

array([[1],
       [2],
       [3]])

In [17]:
np.roll(data, 1)

array([[3],
       [1],
       [2]])

In [47]:
np.roll(data, 2) # same as roll roll pandase has more good way to role usin "shipff"

array([[2],
       [3],
       [1]])

In [18]:
np.roll(data, -2) #rolling in

array([[3],
       [1],
       [2]])

In [19]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [22]:
a = np.array([[[1, 2], [3, 4], [5,6]]])

In [23]:
a

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [24]:
np.roll(a, 2, axis = 0)

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [25]:
#binary operation on array

In [26]:
arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(1, 10, (3, 4))

In [27]:
arr1

array([[8, 9, 3, 5],
       [3, 3, 7, 5],
       [7, 1, 5, 5]])

In [28]:
arr2

array([[6, 1, 2, 3],
       [7, 6, 3, 7],
       [1, 9, 2, 3]])

In [29]:
arr1+arr2

array([[14, 10,  5,  8],
       [10,  9, 10, 12],
       [ 8, 10,  7,  8]])

In [30]:
arr1*arr2

array([[48,  9,  6, 15],
       [21, 18, 21, 35],
       [ 7,  9, 10, 15]])

In [32]:
arr1 / arr2

array([[1.33333333, 9.        , 1.5       , 1.66666667],
       [0.42857143, 0.5       , 2.33333333, 0.71428571],
       [7.        , 0.11111111, 2.5       , 1.66666667]])

In [33]:
arr1 - arr2

array([[ 2,  8,  1,  2],
       [-4, -3,  4, -2],
       [ 6, -8,  3,  2]])

In [34]:
arr1 ** arr2

array([[262144,      9,      9,    125],
       [  2187,    729,    343,  78125],
       [     7,      1,     25,    125]])

In [36]:
arr1

array([[8, 9, 3, 5],
       [3, 3, 7, 5],
       [7, 1, 5, 5]])

In [37]:
arr2

array([[6, 1, 2, 3],
       [7, 6, 3, 7],
       [1, 9, 2, 3]])

In [38]:
arr1 > arr2

array([[ True,  True,  True,  True],
       [False, False,  True, False],
       [ True, False,  True,  True]])

In [39]:
~arr1

array([[ -9, -10,  -4,  -6],
       [ -4,  -4,  -8,  -6],
       [ -8,  -2,  -6,  -6]])

In [40]:
arr1

array([[8, 9, 3, 5],
       [3, 3, 7, 5],
       [7, 1, 5, 5]])

In [41]:
#Numpy string function

In [42]:
arr = np.array(["pw", "skills"])

In [43]:
arr

array(['pw', 'skills'], dtype='<U6')

In [44]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [45]:
np.char.upper(np.array(["Ajay"]))

array(['AJAY'], dtype='<U4')

In [46]:
np.char.capitalize(arr) #only first le

array(['Pw', 'Skills'], dtype='<U6')

In [ ]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [ ]:
#Mathematical function


arr1

array([[2, 7, 1, 6],
       [4, 7, 4, 2],
       [7, 9, 8, 4]])

In [ ]:
np.sin(arr1)

array([[ 0.90929743,  0.6569866 ,  0.84147098, -0.2794155 ],
       [-0.7568025 ,  0.6569866 , -0.7568025 ,  0.90929743],
       [ 0.6569866 ,  0.41211849,  0.98935825, -0.7568025 ]])

In [ ]:
np.cos(arr1)

array([[-0.41614684,  0.75390225,  0.54030231,  0.96017029],
       [-0.65364362,  0.75390225, -0.65364362, -0.41614684],
       [ 0.75390225, -0.91113026, -0.14550003, -0.65364362]])

In [ ]:
np.tan(arr1)

array([[-2.18503986,  0.87144798,  1.55740772, -0.29100619],
       [ 1.15782128,  0.87144798,  1.15782128, -2.18503986],
       [ 0.87144798, -0.45231566, -6.79971146,  1.15782128]])

In [ ]:
np.log10(arr1)

array([[0.30103   , 0.84509804, 0.        , 0.77815125],
       [0.60205999, 0.84509804, 0.60205999, 0.30103   ],
       [0.84509804, 0.95424251, 0.90308999, 0.60205999]])

In [ ]:
np.exp(arr1)

array([[7.38905610e+00, 1.09663316e+03, 2.71828183e+00, 4.03428793e+02],
       [5.45981500e+01, 1.09663316e+03, 5.45981500e+01, 7.38905610e+00],
       [1.09663316e+03, 8.10308393e+03, 2.98095799e+03, 5.45981500e+01]])

In [ ]:
np.power(arr1, 3)

array([[  8, 343,   1, 216],
       [ 64, 343,  64,   8],
       [343, 729, 512,  64]], dtype=int32)

In [ ]:
np.mean(arr1)

5.083333333333333

In [ ]:
np.max(arr1)

9

In [ ]:
np.std(arr1)

2.4986107250941583

In [ ]:
np.var(arr1)

6.243055555555556

In [ ]:
np.max(arr1)

9

In [ ]:
arr1 - arr2

array([[-1, -2, -5, -1],
       [ 2,  0,  0, -5],
       [-2,  6,  2,  1]])

In [ ]:
np.subtract(arr1, arr2)

array([[-1, -2, -5, -1],
       [ 2,  0,  0, -5],
       [-2,  6,  2,  1]])

In [ ]:
arr1 * arr2

array([[ 6, 63,  6, 42],
       [ 8, 49, 16, 14],
       [63, 27, 48, 12]])

In [ ]:
np.multiply(arr1, arr2)

array([[ 6, 63,  6, 42],
       [ 8, 49, 16, 14],
       [63, 27, 48, 12]])

In [ ]:
np.mod(arr1, arr2) #return element wise remainder

array([[2, 7, 1, 6],
       [0, 0, 0, 2],
       [7, 0, 2, 1]])

In [ ]:
np.power(arr1, arr2)

array([[       8, 40353607,        1,   279936],
       [      16,   823543,      256,      128],
       [40353607,      729,   262144,       64]])

In [ ]:
np.sqrt(arr1)

array([[1.41421356, 2.64575131, 1.        , 2.44948974],
       [2.        , 2.64575131, 2.        , 1.41421356],
       [2.64575131, 3.        , 2.82842712, 2.        ]])

In [ ]:
#sort search

In [ ]:
arr = np.array([5, 6, 1, 2])

In [ ]:
arr

array([5, 6, 1, 2])

In [ ]:
np.sort(arr)

array([1, 2, 5, 6])

In [ ]:
arr = np.array([5, 6,100, 200, 1, 2, 8, 9])

In [ ]:
# a = np.sort(arr)

In [ ]:
arr

array([  5,   6, 100, 200,   1,   2,   8,   9])

In [ ]:
np.sort(arr)

array([  1,   2,   5,   6,   8,   9, 100, 200])

In [ ]:
np.searchsorted(arr, 3)

6

In [ ]:
np.searchsorted(arr, 3)

4

In [ ]:
arr1 = np.array([0, 1, 2, 3, 0, 4])
np.count_nonzero(arr1)  #gives number of none zero element

4

In [ ]:
arr1 > 0

array([False,  True,  True,  True, False,  True])

In [ ]:
arr1

array([0, 1, 2, 3, 0, 4])

In [ ]:
np.where(arr1 > 0)

(array([1, 2, 3, 5], dtype=int64),)

In [ ]:
np.extract(arr1 > 0, arr1)

array([1, 2, 3, 4])

In [ ]:
arr1.byteswap() # address

array([       0, 16777216, 33554432, 50331648,        0, 67108864])

In [ ]:
#matrix >> 2d array

In [ ]:
import numpy.matlib as nm #matlib means matrix librery

In [ ]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#Numpy linear algebra

In [ ]:
arr1

array([0, 1, 2, 3, 0, 4])

In [ ]:
arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(1, 10, (3, 4))

In [ ]:
arr1 = np.array([[2, 3], [4, 5]])
arr2 = np.array([[1, 3], [4, 5]])

In [ ]:
arr1 @ arr2

array([[14, 21],
       [24, 37]])

In [ ]:
a  = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])

In [ ]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [ ]:
b = np.array([16, -8, 0])

In [ ]:
b

array([16, -8,  0])

In [ ]:
np.linalg.solve(a, b)  #used to solve liner equestion
#ex:-
#7x + 5.3y - 3z = 16
#3x - 5y + 2z = -8
#5x + 3y - 7z = 0

array([0.90162081, 2.89483603, 1.88465888])

In [ ]:
arr1

array([[2, 3],
       [4, 5]])

In [ ]:
5*2 - 3*4

-2

In [ ]:
np.linalg.det(arr1)
# used to find determin of matrix.

-2.0

In [ ]:
np.linalg.inv(arr1)
# inv used to find inverse of matrix
# For ex:- AA^-1 = I

array([[-2.5,  1.5],
       [ 2. , -1. ]])